[package]
name = "SkipList"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-epoch = "0.9.18"
rand = "0.9.0"
rand_distr = "0.5.0"
rand-unique = "=0.2.2"
criterion = "0.5.1"
skiplist = "0.5.1"

[[bench]]
name = "sk_bench"
harness = false

